version: '2'
services:
  mosquitto:
    image: toke/mosquitto
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/mqtt/config:ro
      - ./logs:/mqtt/logs:rw
    ports:
      - "1883:1883"

      - "8883:8883"
      - "9883:9883"
    networks:
      - mosquitto-nodered
    mem_limit: 1g
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
  
  nodered:
    build: ./nodered
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - volume_nodered:/data:rw
    ports:
      - "443:443"
      - "80:80"
      - "1880:1880"
    networks:
      - mosquitto-nodered

  nifi:
    image: mkobit/nifi:1.0.0-openjdk-8
    restart: always
    volumes:
      - ./config/ca_certificates:/opt/certs
    ports:
      - "8080:8080"
      - "8081:8081"


volumes:
  volume_nodered:
    driver: local

networks:
  mosquitto-nodered:
    driver: bridge